apiVersion: v1
kind: Pod
metadata:
  name: fortune-https
spec:
  containers:
  - image: yj1dreamer/fortune:env
    name: html-generator
    env: 
    - name: INTERVAL
      valueFrom:
        configMapKeyRef:
          key: sleep-interval
          name: fortune-config
    volumeMounts: 
    - name: html
      mountPath: /var/htdocs
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    - name: config
      mountPath: /etc/nginx/conf.d
      readOnly: true
    - name: certs
      mountPath: /etc/nginx/certs/
      readOnly: true
    ports: 
    - containerPort: 80
    - containerPort: 443
  volumes: 
  - name: html
    emptyDir: {}
  - name: config
    configMap:
      name: fortune-config
      items: 
      - key: my-nginx-config.conf
        path: https.conf
  - name: certs
    secret:
      secretName: fortune-https

