apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: kubia2
spec:  
  replicas: 3
  selector: 
    matchExpressions: 
      - key: app
        operator: In
        values: 
          - kubia2 
  template: 
    metadata: 
      labels: 
        app: kubia2
    spec:  
      containers: 
      - name: kubia
        image: luksa/kubia
